In [1]:
import pandas as pd

In [3]:
# 데이터 불러오기
lemon_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/lemonade.csv'
boston_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
iris_path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
lemon = pd.read_csv(lemon_path)
boston = pd.read_csv(boston_path)
iris = pd.read_csv(iris_path)

In [10]:
# 데이터 모양으로 확인하기
print(lemon.shape)
print(boston.shape)
print(iris.shape)

(6, 2)
(506, 14)
(150, 5)

In [13]:
# 칼럼 이름 출력
print(lemon.columns)
print(boston.columns)
print(iris.columns)

Index(['온도', '판매량'], dtype='object')
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')

In [20]:
x = lemon[['온도']]  # 대괄호 하나 사용시 "series" 두개 사용시 "dataframe"
y = lemon[['판매량']]
print(x.shape, y.shape)

(6, 1) (6, 1)

In [22]:
x = boston.drop(['medv'], axis=1) 
y = boston[['medv']]
print(x.shape, y.shape)

(506, 13) (506, 1)

In [23]:
x = iris.drop(['품종'], axis=1)  
y = iris[['품종']]
print(x.shape, y.shape)

(150, 4) (150, 1)

In [24]:
# 출력

In [26]:
lemon.head()

   온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [28]:
boston.head()

      crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [29]:
iris.head()

   꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa